spring:
  datasource:
    # Configure your production datasource via environment variables or secrets
    # Example for PostgreSQL:
    # url: ${DB_URL}
    # driver-class-name: org.postgresql.Driver
    # username: ${DB_USERNAME}
    # password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.studywave: INFO
    org.springframework.security: INFO
